name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: PHP
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']
        phpunit: ['latest']
        include:
          - php: '7.4'
            phpunit: '8.5.13'

    services:
      mysql:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Use PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@2.18.1
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, curl, zip, dom, simplexml, intl, pdo_mysql
          tools: phpunit:${{ matrix.phpunit }}

      - name: Install the YOURLS test suite for plugins
        run: |
          git clone --depth 1 https://github.com/YOURLS/YOURLS-test-suite-for-plugins test-suite
          bash test-suite/src/install-test-suite.sh yourls_tests root '' 127.0.0.1

      - name: Check files
        run: |
          echo "Working directory: $(pwd)"
          ls -la

      - name: Run the tests
        run: phpunit -c ./test-suite/src/phpunit.xml
